export const LEDGER_EVENT_TYPES = [
  "PREDICTION_DRAFT_CREATED",
  "PREDICTION_DRAFT_UPDATED",
  "PREDICTION_PUBLISHED",
  "PREDICTION_PUBLICATION_REVISED",
  "PREDICTION_WITHDRAWN",
  "PREDICTION_SETTLEMENT_RECORDED",
  "PREDICTION_SETTLEMENT_CORRECTED",
  "FIXTURE_STATE_OBSERVED",
  "FIXTURE_FINAL_STATE_RECORDED",
  "FIXTURE_SETTLEMENT_RECORDED",
  "FIXTURE_SETTLEMENT_CORRECTED",
  "BUILDER_GENERATION_REQUESTED",
  "BUILDER_CANDIDATE_SNAPSHOT_RECORDED",
  "BUILDER_CANDIDATE_EXCLUDED",
  "BUILDER_COMBINATION_CREATED",
  "BUILDER_GENERATION_COMPLETED",
  "BUILDER_GENERATION_FAILED",
  "BUILDER_COMBINATION_TRANSFERRED",
  "BUILDER_TRANSFER_MERGED",
  "BUILDER_TRANSFER_REPLACED",
  "STUDIO_SELECTION_ADDED",
  "STUDIO_SELECTION_REMOVED",
  "STUDIO_HANDOFF_REQUESTED",
  "STUDIO_HANDOFF_CREATED",
  "STUDIO_HANDOFF_FAILED",
  "BUILDER_LEG_SETTLEMENT_LINKED",
  "BUILDER_COMBINATION_SETTLEMENT_RECORDED",
  "BUILDER_COMBINATION_SETTLEMENT_CORRECTED",
  "LEDGER_BACKFILL_RECORDED",
  "LEDGER_RECONCILIATION_COMPLETED",
  "LEDGER_INTEGRITY_FAILURE_DETECTED",
] as const;

export type LedgerEventType = (typeof LEDGER_EVENT_TYPES)[number];

export function isLedgerEventType(raw: string): raw is LedgerEventType {
  return (LEDGER_EVENT_TYPES as readonly string[]).includes(raw);
}
