import type { PlacementRecord } from "./contracts";

/**
 * Static placement inventory derived from real signing / CTA sites.
 * Competition/team/market/season link to operator pages (not /go) — documented.
 */
export const AFFILIATE_PLACEMENTS: readonly PlacementRecord[] = [
  /*
   * Commercial conversion pass (Phase D): every conversion point emits its
   * placement, so admin/affiliate/funnels can answer "which points convert".
   * price_panel and the per-surface operator cards sign through buildGoPath
   * and appear in redirect events under these ids; the post-L2 bridge is a
   * same-page anchor (no redirect) and is measured by its data-placement
   * attribute at the click layer.
   */
  {
    placementId: "price_panel",
    pageType: "fixture",
    componentPath: "components/odds/PricePanel.tsx",
    userIntentStage: "conversion",
    operatorSelection: "buildPricePanelData (frozen publication odds, availability→verified→price)",
    attributionSchema: ["operator", "placement", "fixture", "market", "locale", "country"],
    signingMethod: "buildPricePanelData → buildGoPath",
    availabilityRule: "resolveOperatorAvailability + affiliateEnabled (Continue gated)",
    fallbackBehavior: "no observation → no affordance, no panel",
    eventNames: ["operator_click", "affiliate_redirect_created"],
    duplicateCtaRisk: "low",
    prominence: "secondary",
    qualityStatus: "ok",
    notes: ["Also rendered on market-page fixture rows for the page's market."],
  },
  {
    placementId: "operator_card_fixture",
    pageType: "fixture",
    componentPath: "components/operators/OperatorEvidenceCard.tsx",
    userIntentStage: "conversion",
    operatorSelection: "recommendableCards(buildOperatorEvidenceCards)",
    attributionSchema: ["operator", "placement", "locale", "country"],
    signingMethod: "operatorAffiliateHref(placement=operator_card_fixture) → buildGoPath",
    availabilityRule: "affiliateEnabled; internal profile fallback otherwise",
    fallbackBehavior: "internal operator page (never an outbound link)",
    eventNames: ["operator_card_impression", "operator_card_primary_click", "affiliate_redirect_created"],
    duplicateCtaRisk: "low",
    prominence: "primary",
    qualityStatus: "ok",
    notes: ["operator_card_competition and operator_card_market are the same site on their surfaces."],
  },
  {
    placementId: "post_l2_bridge",
    pageType: "fixture",
    componentPath: "components/fixtures/FixtureSignalLevels.tsx",
    userIntentStage: "research",
    operatorSelection: "none — same-page anchor to the L5 operators level",
    attributionSchema: ["placement", "locale"],
    signingMethod: "none (no redirect; data-placement attribute only)",
    availabilityRule: "renders whenever L2 renders",
    fallbackBehavior: "absent with the supports level",
    eventNames: [],
    duplicateCtaRisk: "low",
    prominence: "tertiary",
    qualityStatus: "ok",
    notes: ["A bridge, not a CTA: it converts attention to L5, not clicks to operators."],
  },
  {
    placementId: "homepage_operator",
    pageType: "home",
    componentPath: "components/bible/BibleOperatorStrip.tsx",
    userIntentStage: "discovery",
    operatorSelection: "personalized homepage ranking",
    attributionSchema: ["operator", "placement", "locale", "country"],
    signingMethod: "buildGoPath (server)",
    availabilityRule: "brandsForCountry + affiliate configured",
    fallbackBehavior: "omit unconfigured brands",
    eventNames: ["operator_impression", "operator_click", "go_redirect"],
    duplicateCtaRisk: "medium",
    prominence: "primary",
    qualityStatus: "ok",
    notes: ["Signed via lib/personalization/homepage.ts"],
  },
  {
    placementId: "fixture_operator",
    pageType: "fixture",
    componentPath: "components/bible/BibleFixtureExplorer.tsx + MatchDetailView",
    userIntentStage: "research",
    operatorSelection: "signAffiliateOffers / match-detail API",
    attributionSchema: ["operator", "placement", "fixture", "market", "locale"],
    signingMethod: "signAffiliateOffers → buildGoPath",
    availabilityRule: "resolveAffiliateOffers + country",
    fallbackBehavior: "empty partner list when none available",
    eventNames: ["operator_impression", "operator_click", "affiliate_redirect_created"],
    duplicateCtaRisk: "medium",
    prominence: "primary",
    qualityStatus: "ok",
    notes: [],
  },
  {
    placementId: "operator_page",
    pageType: "operator",
    componentPath: "components/operators/OperatorDetailView.tsx",
    userIntentStage: "operator_evaluation",
    operatorSelection: "single operator page",
    attributionSchema: ["operator", "placement"],
    signingMethod: "operatorAffiliateHref → buildGoPath",
    availabilityRule: "affiliateEnabled + configured URL",
    fallbackBehavior: "review page / no CTA when unconfigured",
    eventNames: ["operator_affiliate_cta_click", "go_redirect"],
    duplicateCtaRisk: "low",
    prominence: "primary",
    qualityStatus: "ok",
    notes: [],
  },
  {
    placementId: "review_page",
    pageType: "review",
    componentPath: "app/[locale]/reviews/[brand]/page.tsx",
    userIntentStage: "operator_evaluation",
    operatorSelection: "brand review",
    attributionSchema: ["operator", "placement"],
    signingMethod: "buildGoPath",
    availabilityRule: "brand present",
    fallbackBehavior: "text without outbound when unconfigured",
    eventNames: ["go_redirect"],
    duplicateCtaRisk: "low",
    prominence: "secondary",
    qualityStatus: "ok",
    notes: [],
  },
  {
    placementId: "compare_page",
    pageType: "compare",
    componentPath: "app/[locale]/compare/[slug]/page.tsx",
    userIntentStage: "comparison",
    operatorSelection: "compare pair",
    attributionSchema: ["operator", "placement"],
    signingMethod: "buildGoPath",
    availabilityRule: "indexable/compare rules",
    fallbackBehavior: "link omitted when unconfigured",
    eventNames: ["go_redirect"],
    duplicateCtaRisk: "medium",
    prominence: "secondary",
    qualityStatus: "ok",
    notes: [],
  },
  /*
   * brand_list RETIRED (commercial conversion): BrandList and its host pages
   * (bonuses / best-* hubs) are deleted; the doors are permanent redirects
   * into /operators. The record is removed rather than kept as a ghost — a
   * funnel row for a component that cannot render is a false signal.
   */
  {
    placementId: "acca_studio",
    pageType: "acca_studio",
    componentPath: "components/acca/AccaOperators.tsx",
    userIntentStage: "conversion",
    operatorSelection: "POST /api/acca/operators",
    attributionSchema: ["operator", "placement", "locale", "acca_context"],
    signingMethod: "buildAccaOperatorOffers → buildGoPath",
    availabilityRule: "server operator eligibility",
    fallbackBehavior: "empty operator list",
    eventNames: [
      "acca_operator_selected",
      "acca_affiliate_handoff",
      "affiliate_redirect_created",
    ],
    duplicateCtaRisk: "low",
    prominence: "primary",
    qualityStatus: "ok",
    notes: [],
  },
  {
    placementId: "combo_studio",
    pageType: "combo",
    componentPath: "components/combo/ComboOperatorCard.tsx",
    userIntentStage: "conversion",
    operatorSelection: "matchOperatorsForCombo",
    attributionSchema: ["operator", "placement", "comboId"],
    signingMethod: "buildGoPath in combo operators",
    availabilityRule: "listEligibleOperators",
    fallbackBehavior: "unknown / unavailable cards",
    eventNames: ["combo_operator_click", "go_redirect"],
    duplicateCtaRisk: "low",
    prominence: "secondary",
    qualityStatus: "review",
    notes: ["Legacy combo surface; /combo redirects to Acca Builder"],
  },
  {
    placementId: "acca_builder_handoff",
    pageType: "acca_builder",
    componentPath: "components/acca-builder/AccaBuilderView.tsx",
    userIntentStage: "conversion",
    operatorSelection: "transfer to Studio (no direct /go)",
    attributionSchema: ["placement", "risk_mode"],
    signingMethod: "none — Studio signs later",
    availabilityRule: "n/a until Studio",
    fallbackBehavior: "open Acca Studio",
    eventNames: ["acca_builder_added_to_studio", "acca_builder_operator_handoff"],
    duplicateCtaRisk: "low",
    prominence: "utility",
    qualityStatus: "issue",
    notes: [
      "acca_builder_operator_handoff defined but not emitted in Builder UI today",
    ],
  },
  {
    placementId: "competition_operator_link",
    pageType: "competition",
    componentPath: "components/competitions/CompetitionDetailView.tsx",
    userIntentStage: "research",
    operatorSelection: "link to operator page (not /go)",
    attributionSchema: ["operator"],
    signingMethod: "none (operatorPath)",
    availabilityRule: "registry listing",
    fallbackBehavior: "no outbound affiliate",
    eventNames: ["competition_operator_click"],
    duplicateCtaRisk: "low",
    prominence: "tertiary",
    qualityStatus: "ok",
    notes: ["Does not create signed redirect"],
  },
  {
    placementId: "team_operator_link",
    pageType: "team",
    componentPath: "components/teams/TeamDetailView.tsx",
    userIntentStage: "research",
    operatorSelection: "link to operator page (not /go)",
    attributionSchema: ["operator"],
    signingMethod: "none (operatorPath)",
    availabilityRule: "registry listing",
    fallbackBehavior: "no outbound affiliate",
    eventNames: ["team_operator_click"],
    duplicateCtaRisk: "low",
    prominence: "tertiary",
    qualityStatus: "ok",
    notes: [],
  },
  {
    placementId: "go_redirect_fallback",
    pageType: "redirect",
    componentPath: "app/go/[brand]/route.ts",
    userIntentStage: "conversion",
    operatorSelection: "ctx placement or go_redirect",
    attributionSchema: ["operator", "placement", "subid", "requestId"],
    signingMethod: "verifyRedirectToken server-side",
    availabilityRule: "country_ineligible + host allowlist",
    fallbackBehavior: "safe error / review page",
    eventNames: [
      "affiliate_redirect_created",
      "affiliate_redirect_completed",
      "affiliate_redirect_failed",
      "operator_click",
      "go_redirect",
    ],
    duplicateCtaRisk: "low",
    prominence: "utility",
    qualityStatus: "ok",
    notes: ["Rejects client destination overrides"],
  },
];

export function placementById(id: string): PlacementRecord | undefined {
  return AFFILIATE_PLACEMENTS.find((p) => p.placementId === id);
}
